# Generated by Django 4.2.13 on 2024-07-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentrequest',
            old_name='accepted',
            new_name='is_accepted',
        ),
    ]
