# Generated by Django 4.2.13 on 2024-07-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_rename_accepted_rentrequest_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentadvertisement',
            name='request_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
